//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CockatriceDeckTemplateBuilder.Main.Database.databasev2
{

    public partial class CardReference : XPObject
    {
        TemplateItem _usedInTemplates;
        public TemplateItem UsedInTemplates
        {
            get { return _usedInTemplates; }
            set { SetPropertyValue<TemplateItem>(nameof(UsedInTemplates), ref _usedInTemplates, value); }
        }
        string _card;
        public string Card
        {
            get { return _card; }
            set { SetPropertyValue<string>(nameof(Card), ref _card, value); }
        }
        long _count;
        public long Count
        {
            get { return _count; }
            set { SetPropertyValue<long>(nameof(Count), ref _count, value); }
        }
        [Browsable(false)]
        [Association()]
        public IList<TemplateItemReferencesCardReference> TemplateItemReferencesCardReference { get { return GetList<TemplateItemReferencesCardReference>(nameof(TemplateItemReferencesCardReference)); } }

        [ManyToManyAlias("TemplateItemReferencesCardReference", "TemplateItems")]
        public IList<TemplateItem> TemplateItems
        {
            get
            {
                return GetList<TemplateItem>("TemplateItems");
            }
        }
    }

    [Persistent("TemplateItemTemplateItems_CardReferenceCardReferences")]
    public class TemplateItemReferencesCardReference : PersistentBase
    {
        public TemplateItemReferencesCardReference(Session session) : base(session) { }
        [Key(true)]
        public int Oid;
        private TemplateItem _TemplateItems;
        [Association]
        public TemplateItem TemplateItems
        {
            get { return _TemplateItems; }
            set { SetPropertyValue("TemplateItems", ref _TemplateItems, value); }
        }
        private CardReference _CardReferences;
        [Association]
        public CardReference CardReferences
        {
            get { return _CardReferences; }
            set { SetPropertyValue("CardReferences", ref _CardReferences, value); }
        }
    }
}
