//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CockatriceDeckTemplateBuilder.Main.Database.databasev2
{

    public partial class TemplateItem : XPObject
    {
        TemplateCategory _category;
        [Association(@"TemplateItemReferencesTemplateCategories")]
        public TemplateCategory Category
        {
            get { return _category; }
            set { SetPropertyValue<TemplateCategory>(nameof(Category), ref _category, value); }
        }
        string _name;
        public string Name
        {
            get { return _name; }
            set { SetPropertyValue<string>(nameof(Name), ref _name, value); }
        }
        string _description;
        public string Description
        {
            get { return _description; }
            set { SetPropertyValue<string>(nameof(Description), ref _description, value); }
        }
        string _colors;
        public string Colors
        {
            get { return _colors; }
            set { SetPropertyValue<string>(nameof(Colors), ref _colors, value); }
        }
        [Browsable(false)]
        [Association()]
        public IList<TemplateItemReferencesCardReference> TemplateItemReferencesCardReference { get { return GetList<TemplateItemReferencesCardReference>(nameof(TemplateItemReferencesCardReference)); } }

        [ManyToManyAlias("TemplateItemReferencesCardReference", "CardReferences")]
        public IList<CardReference> CardReferences
        {
            get
            {
                return GetList<CardReference>("CardReferences");
            }
        }
    }

}
