using DevExpress.XtraBars.Docking;
using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Windows.Forms;

namespace CockatriceDeckTemplateBuilder.Main.ToolWindows
{
    public partial class CardDataBase : TabDocBase
    {
        private DockPanel _dockPanel;
        bool isParent = false;

        public CardDataBase()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the JsonDataSource asynchronously
            jsonDataSource1.FillAsync();
        }

        public DockPanel LoadControl(DockManager dockManager)
         => dockManager.AddPanel(this, DockingStyle.Fill, "Card Database");
        

    }
    public partial class TabDocBase : XtraUserControl
    {
        public delegate void PageRemovedHandler();
        public event PageRemovedHandler PageRemoved;

        public List<TabDocBase> Pages => AddPage();
        public bool IsParent { get; private set; }
        public List<TabDocBase> AddPage()
        {
            var _pages = Pages ?? new List<TabDocBase>();
            var count = _pages.FindAll(page => page.IsParent).Count;
            if (_pages.FindAll(page => page.IsParent).Count > 1)IsParent = false;
            else if (count == 0) _pages.Add(this);
            return _pages;
        }



    }

}
